# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Framework
version:      0.11
version_from: lib/CGI/Framework.pm
installdirs:  site
requires:
    CGI:                           0
    CGI::Carp:                     0
    CGI::Session:                  0
    HTML::Template:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
